---
permalink: rhel-install/task-configure-authentication-settings.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, configure, authentication, settings 
summary: 'Vous pouvez configurer OnCommand Workflow Automation (WFA) pour qu"il utilise un serveur Microsoft Active Directory (AD) LDAP (Lightweight Directory Access Protocol) à des fins d"authentification et d"autorisation.' 
---
= Configurer les paramètres d'authentification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer OnCommand Workflow Automation (WFA) pour qu'il utilise un serveur Microsoft Active Directory (AD) LDAP (Lightweight Directory Access Protocol) à des fins d'authentification et d'autorisation.

Vous devez avoir configuré un serveur LDAP Microsoft AD dans votre environnement.

Seule l'authentification LDAP Microsoft AD est prise en charge pour WFA. Vous ne pouvez pas utiliser d'autres méthodes d'authentification LDAP, notamment Microsoft AD Lightweight Directory Services (AD LDS) ou Microsoft Global Catalog.


NOTE: Lors de la communication, LDAP envoie le nom d'utilisateur et le mot de passe en texte brut. Cependant, les communications LDAPS (LDAP Secure) sont cryptées et sécurisées.

.Étapes
. Connectez-vous à WFA via un navigateur Web en tant qu'administrateur.
. Ajoutez une liste de noms de groupe Active Directory aux rôles requis.
+

NOTE: Vous pouvez ajouter une liste de noms de groupes AD aux rôles requis dans la fenêtre groupes Active Directory.

+
xref:task-add-active-directory-group-names.adoc[La fenêtre groupes Active Directory]

. Cliquez sur *Administration* > *WFA Configuration*.
. Dans la boîte de dialogue Configuration de WFA, cliquez sur l'onglet *authentification*, puis cochez la case *Activer Active Directory*.
. Entrez les informations requises dans les champs :
+
.. Si vous souhaitez utiliser le format user@domain pour les utilisateurs de domaine, remplacez sAMAccountName par userPrincipalName dans le champ *User name attribute*.
.. Si des valeurs uniques sont requises pour votre environnement, modifiez les champs obligatoires.


. Cliquez sur *Ajouter* pour ajouter Active Directory dans la table serveurs Active Directory au format URI : `ldap://active_directory_server_address\[:port\]`
+
ldap://NB-T01.example.com[:389]

+
Si vous avez activé LDAP sur SSL, vous pouvez utiliser le format URI suivant : `ldaps://active_directory_server_address\[:port\]`

. Fournissez les informations d'identification pour lier le serveur LDAP et le DN de base.
. Tester l'authentification de l'utilisateur donné :
+
.. Entrez le nom d'utilisateur et le mot de passe.
.. Cliquez sur *Tester l'authentification*.


+

NOTE: Vous devez avoir ajouté le groupe Active Directory pour tester l'authentification de l'utilisateur donné dans WFA.

. Cliquez sur *Enregistrer*.

