---
permalink: rhel-install/task-reset-the-admin-password-created-during-installation-linux.html 
sidebar: sidebar 
keywords: reset, admin password, created, installation 
summary: 'Si vous avez oublié le mot de passe de l"utilisateur admin que vous avez créé lors de l"installation du serveur OnCommand Workflow Automation (WFA), vous pouvez le réinitialiser.' 
---
= Réinitialise le mot de passe d'administration créé lors de l'installation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez oublié le mot de passe de l'utilisateur admin que vous avez créé lors de l'installation du serveur OnCommand Workflow Automation (WFA), vous pouvez le réinitialiser.

* Vous devez disposer de privilèges root pour le système Linux sur lequel vous avez installé WFA.
* Les services WFA doivent être en cours d'exécution.
* Cette procédure réinitialise uniquement le mot de passe de l'utilisateur admin créé lors de l'installation de WFA.
+
Vous ne pouvez pas réinitialiser le mot de passe des autres utilisateurs admin de WFA que vous avez créés après l'installation de WFA.

* Cette procédure n'applique pas la stratégie de mot de passe que vous avez configurée.
+
Par conséquent, vous devez entrer un mot de passe conforme à la politique de mots de passe ou modifier ce mot de passe depuis l'interface utilisateur WFA après avoir réinitialisé le mot de passe.



.Étapes
. En tant qu'utilisateur root, connectez-vous au système Linux sur lequel WFA est installé.
. À l'invite du shell, accédez au répertoire suivant sur le serveur WFA : WFA_install_location/wfa/bin/
. Saisissez la commande suivante :
+
`./wfa --admin-password [--password=PASS]`

+
Si vous n'avez pas fourni de mot de passe, vous devez entrer ce mot de passe.

. À l'invite du shell, suivez les instructions à l'écran.

