---
permalink: rhel-install/task-back-up-regular-the-wfa-database-using-perl-script-linux.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, back up, regular, wfa database, cli 
summary: 'Vous pouvez effectuer une sauvegarde régulière de la base de données OnCommand Workflow Automation (WFA) à l"aide de l"interface de ligne de commandes WFA. Lors d"une sauvegarde régulière, seule la base de données WFA est sauvegardée.' 
---
= Sauvegardez (régulièrement) la base de données WFA à l'aide de l'interface de ligne de commande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer une sauvegarde régulière de la base de données OnCommand Workflow Automation (WFA) à l'aide de l'interface de ligne de commandes WFA. Lors d'une sauvegarde régulière, seule la base de données WFA est sauvegardée.

Vous devez disposer des informations d'identification de l'utilisateur administrateur, des informations d'identification d'architecte ou des informations d'identification de l'utilisateur de sauvegarde.

Dans un environnement à haute disponibilité, vous devez créer des sauvegardes planifiées à l'aide d'API REST. Vous ne pouvez pas créer de sauvegardes via l'interface de ligne de commandes lorsque WFA est en mode de basculement.

Pour plus d'informations, consultez la documentation REST.

.Étapes
. À l'invite du shell, accédez au répertoire suivant sur le serveur WFA : WFA_install_location/wfa/bin/.
+
WFA_install_location est le répertoire d'installation de WFA.

. Sauvegarder la base de données WFA : `.\wfa --backup --user=USER [--password=PASS] [--location=PATH]`
+
** user est le nom d'utilisateur de l'utilisateur de sauvegarde.
** mot de passe est le mot de passe de l'utilisateur de sauvegarde.
+
Si vous n'avez pas fourni le mot de passe, vous devez entrer le mot de passe lorsque vous y êtes invité.

** chemin est le chemin complet du répertoire vers le fichier de sauvegarde.


. Vérifiez que le fichier de sauvegarde a été créé à l'emplacement spécifié.

