---
permalink: rhel-install/task-disable-the-default-password-policy-linux.html 
sidebar: sidebar 
keywords: disable, default, password policy 
summary: 'OnCommand Workflow Automation (WFA) est configuré pour appliquer une politique de mots de passe aux utilisateurs locaux. Si vous ne souhaitez pas utiliser la stratégie de mot de passe, vous pouvez la désactiver.' 
---
= Désactivez la stratégie de mot de passe par défaut
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) est configuré pour appliquer une politique de mots de passe aux utilisateurs locaux. Si vous ne souhaitez pas utiliser la stratégie de mot de passe, vous pouvez la désactiver.

Vous devez avoir ouvert une session sur le système hôte WFA en tant qu'utilisateur root.

Le chemin d'installation par défaut de WFA est utilisé dans cette procédure. Si vous avez modifié l'emplacement par défaut lors de l'installation, vous devez utiliser le chemin d'installation WFA modifié.

.Étapes
. À l'invite du shell, accédez au répertoire suivant sur le serveur WFA : WFA_install_location/wfa/bin/
. Saisissez la commande suivante :
+
`./wfa --password-policy=none --restart=WFA`


