---
permalink: rhel-install/task-configure-the-timeout-value-for-linux.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, configure, timeout value 
summary: 'Vous pouvez configurer la valeur du délai d"attente pour l"interface graphique Web de Workflow Automation (WFA), au lieu d"utiliser la valeur par défaut du délai d"expiration de 180 secondes.' 
---
= Configurez la valeur du délai d'expiration pour Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer la valeur du délai d'attente pour l'interface graphique Web de Workflow Automation (WFA), au lieu d'utiliser la valeur par défaut du délai d'expiration de 180 secondes.

La valeur de temporisation que vous avez définie correspond à un délai d'inactivité absolu plutôt qu'à un délai d'inactivité. Par exemple, si vous définissez cette valeur sur 30 minutes, vous êtes déconnecté après 30 minutes, même si vous êtes actif à la fin de cette période. Vous ne pouvez pas définir la valeur de temporisation à partir de l'interface Web de WFA.

.Étapes
. Connectez-vous en tant qu'utilisateur root sur la machine hôte WFA.
. Définissez la valeur de temporisation :
+
`installdir bin/wfa -S=timeout value in minutes`


