---
permalink: rhel-install/task-back-up-the-wfa-database-and-configurations-linux.html 
sidebar: sidebar 
keywords: back up, restore, oncommand, workflow, automation, database, configurations, linux 
summary: 'Vous pouvez sauvegarder et restaurer la base de données OnCommand Workflow Automation (WFA) et les configurations prises en charge, afin de pouvoir restaurer les données en cas d"incident. Les configurations prises en charge incluent l"accès aux données, le délai d"attente HTTP et les certificats SSL.' 
---
= Sauvegarde et restauration de la base de données et des configurations OnCommand Workflow Automation sous Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez sauvegarder et restaurer la base de données OnCommand Workflow Automation (WFA) et les configurations prises en charge, afin de pouvoir restaurer les données en cas d'incident. Les configurations prises en charge incluent l'accès aux données, le délai d'attente HTTP et les certificats SSL.

Vous devez disposer des privilèges d'administrateur ou des informations d'identification d'architecte.

Vous devez créer la sauvegarde dans un emplacement sécurisé, car la restauration de la sauvegarde permet d'accéder à tous les systèmes de stockage auxquels WFA accède.

[NOTE]
====
* Une sauvegarde complète des bases de données et des configurations WFA est requise pendant la reprise sur incident et peut être utilisée dans des environnements autonomes ou haute disponibilité.
* Vous pouvez utiliser uniquement les commandes de l'interface de ligne de commandes ou les API REST pour réaliser des opérations de sauvegarde et de restauration complètes pendant la reprise d'activité.
+
Vous ne pouvez pas utiliser l'interface utilisateur Web pour sauvegarder ou restaurer la base de données WFA pendant la reprise d'activité.



====
.Étapes
. Sauvegardez la base de données OnCommand Workflow Automation.
+
link:reference-backing-up-of-the-oncommand-workflow-automation-database.html["Sauvegarde de la base de données OnCommand Workflow Automation"]

. Restaurez une sauvegarde précédente de la base de données OnCommand Workflow Automation.
+
link:concept-restoring-the-wfa-database.html["Restauration de la base de données OnCommand Workflow Automation"]


