---
permalink: rhel-install/task-modify-the-default-password-policy-linux.html 
sidebar: sidebar 
keywords: modify, default, password policy 
summary: 'OnCommand Workflow Automation (WFA) est configuré pour appliquer une politique de mots de passe aux utilisateurs locaux. Vous pouvez modifier la stratégie de mot de passe par défaut.' 
---
= Modifier la stratégie de mots de passe par défaut
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) est configuré pour appliquer une politique de mots de passe aux utilisateurs locaux. Vous pouvez modifier la stratégie de mot de passe par défaut.

Vous devez avoir ouvert une session sur le système hôte WFA en tant qu'utilisateur root.

* Le chemin d'installation par défaut de WFA est utilisé dans cette procédure.
+
Si vous avez modifié l'emplacement par défaut lors de l'installation, vous devez utiliser le chemin d'installation WFA modifié.

* La commande de la stratégie de mot de passe par défaut est ./wfa --password-policy=default.
+
La valeur par défaut est "minLength=true,8;specialChar=true,1;digitalChar=true,1;lowercasChar=true,1;uppercaseChar=true,1;blanceChar=false` . Cela indique que la stratégie de mot de passe par défaut doit comporter au moins huit caractères, dont au moins 1 caractère spécial, 1 chiffre, 1 caractère minuscule, 1 caractère majuscule et aucun espace.



.Étapes
. À l'invite du shell, accédez au répertoire suivant sur le serveur WFA : WFA_install_location/wfa/bin/
. Modifiez la politique de mots de passe par défaut en entrant la commande suivante :
+
`./wfa --password-policy=PasswordPolicyString --restart=WFA`


