---
settings:
  name: OnCommand Workflow Automation 5.1
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation OnCommand Workflow Automation 5.1
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/reference-releasenotes.html"
  - section: rhel-install
  - section: windows-install
  - section: workflow
  - section: help
  - title: Mentions légales
    url: "/reference-legal-notices.html"
