---
settings:
  name: OnCommand Workflow Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documents OnCommand Workflow Automation
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/reference-releasenotes.html"
  - section: rhel-install
  - section: windows-install
  - section: workflow
  - section: help
  - title: Mentions légales
    url: "/reference-legal-notices.html"
