---
settings:
  name: OnCommand Workflow Automation 5.1
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,zh-cn,zh-tw,ko-kr,de-de
sidebar:
  entries:
  - title: Documentation OnCommand Workflow Automation 5.1
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/reference-releasenotes.html"
  - section: rhel-install
  - section: windows-install
  - section: workflow
  - section: help
  - title: Mentions légales
    url: "/reference-legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Notes de version
      url: reference-releasenotes.html
  - title: Installation et configuration sur les systèmes Linux
    links:
    - title: Configuration système requise pour l'installation de OnCommand Workflow
        Automation
      url: rhel-install/reference-system-requirements-for-oncommand-workflow-automation-linux.html
    - title: Gérer la haute disponibilité
      url: rhel-install/concept-managing-high-availability.html
    - title: Configurer OnCommand Workflow Automation
      url: rhel-install/concept-setting-up-oncommand-workflow-automation.html
    - title: Sauvegardez la base de données OnCommand Workflow Automation
      url: rhel-install/reference-backing-up-of-the-oncommand-workflow-automation-database.html
    - title: Restaurez la base de données OnCommand Workflow Automation
      url: rhel-install/concept-restoring-the-wfa-database.html
    - title: Désinstaller OnCommand Workflow Automation
      url: rhel-install/task-uninstall-oncommand-workflow-automation-linux.html
    - title: Résoudre les problèmes d'installation et de configuration
      url: rhel-install/reference-troubleshooting.html
  - title: Installation et configuration sur les systèmes Windows
    links:
    - title: Configuration système requise pour l'installation de OnCommand Workflow
        Automation
      url: windows-install/reference-system-requirements-for-oncommand-workflow-automation-windows.html
    - title: Installez OnCommand Workflow Automation sous Windows
      url: windows-install/task-install-workflow-automation-on-windows.html
    - title: Configurer OnCommand Workflow Automation
      url: windows-install/concept-setting-up-oncommand-workflow-automation.html
    - title: Sauvegardez la base de données OnCommand Workflow Automation
      url: windows-install/reference-backing-up-of-the-oncommand-workflow-automation-database.html
    - title: Restaurez la base de données OnCommand Workflow Automation
      url: windows-install/concept-restoring-the-wfa-database.html
    - title: Désinstaller OnCommand Workflow Automation
      url: windows-install/task-uninstall-oncommand-workflow-automation.html
    - title: Résoudre les problèmes d'installation et de configuration
      url: windows-install/reference-troubleshooting.html
  - title: Création et gestion des flux de travail
    links:
    - title: Gestion des flux de travail
      url: workflows/concept-managing-workflows.html
  - title: Plus d'informations
    links:
    - title: Communauté NetApp
      url: http://community.netapp.com/t5/OnCommand-Storage-Management-Software-Articles-and-Resources/tkb-p/oncommand-storage-management-software-articles-and-resources/label-name/workflow%20automation%20%28wfa%29?labels=workflow+automation+%28wfa%29
    - title: Matrice d'interopérabilité
      url: http://mysupport.netapp.com/matrix/
