---
permalink: reference-legal-notices.html 
sidebar: sidebar 
keywords: legal, notices, copyright, trademarks, patents 
summary: Les mentions légales donnent accès aux déclarations de copyright, aux marques, aux brevets, etc. 
---
= Mentions légales
:allow-uri-read: 


Les mentions légales donnent accès aux déclarations de copyright, aux marques, aux brevets, etc.



== Droits d'auteur

http://www.netapp.com/us/legal/copyright.aspx[]



== Marques déposées

NetApp, le logo NETAPP et les marques mentionnées sur la page des marques commerciales NetApp sont des marques commerciales de NetApp, Inc. Les autres noms de sociétés et de produits peuvent être des marques commerciales de leurs propriétaires respectifs.

http://www.netapp.com/us/legal/netapptmlist.aspx[]



== Brevets

Vous trouverez une liste actuelle des brevets appartenant à NetApp à l'adresse suivante :

https://www.netapp.com/us/media/patents-page.pdf[]



== Politique de confidentialité

https://www.netapp.com/us/legal/privacypolicy/index.aspx[]



== Avertissement

Les fichiers de notification fournissent des informations sur les droits d'auteur et les licences de tiers utilisés dans le logiciel NetApp.

link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2875136["Remarque concernant Workflow Automation 5.1.1"^]

link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2861741["Remarque concernant Workflow Automation 5.1"^]
