---
permalink: windows-install/task-regular-restore-of-the-oncommand-workflow-automation-database-using-clis-windows.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, restore, regular, wfa, database, cli 
summary: 'Vous pouvez effectuer régulièrement une restauration de la base de données OnCommand Workflow Automation (WFA) à l"aide des API REST. Lors d"une restauration régulière, vous pouvez uniquement sauvegarder la base de données WFA.' 
---
= Restauration (régulière) de la base de données WFA à l'aide de l'interface de ligne de commandes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer régulièrement une restauration de la base de données OnCommand Workflow Automation (WFA) à l'aide des API REST. Lors d'une restauration régulière, vous pouvez uniquement sauvegarder la base de données WFA.

* Vous devez avoir créé une sauvegarde de la base de données WFA.
* Vous devez disposer des informations d'identification administrateur, des informations d'identification d'architecte ou des informations d'identification de l'utilisateur de sauvegarde.


.Étapes
. À l'invite du shell, accédez au répertoire suivant sur le serveur WFA : WFA_install_location\WFA\bin
+
wfa_install_location est le répertoire d'installation de WFA.

. Effectuez l'opération de restauration :
+
`wfa.cmd --restore --user=user_name [--password=password] [--location=path]`

+
** nom_utilisateur est le nom d'utilisateur de l'utilisateur admin ou architecte.
** le mot de passe est le mot de passe de l'utilisateur.
+
Si vous n'avez pas fourni le mot de passe, vous devez entrer le mot de passe lorsque vous y êtes invité.

** chemin est le chemin complet du répertoire vers le fichier de restauration.


. Vérifiez que l'opération de restauration est réussie et que WFA est accessible.

