---
permalink: windows-install/task-configure-a-database-user-by-running-ocsetup-on-windows.html 
sidebar: sidebar 
keywords: configure, database, user, run, ocsetup, windows 
summary: 'Vous pouvez exécuter le fichier ocsetup sur le serveur DataFabric Manager 5.x pour configurer l"accès en lecture seule de la base de données DataFabric Manager 5.x à OnCommand Workflow Automation.' 
---
= Configurez un utilisateur de base de données en exécutant ocsetup sous Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter le fichier ocsetup sur le serveur DataFabric Manager 5.x pour configurer l'accès en lecture seule de la base de données DataFabric Manager 5.x à OnCommand Workflow Automation.

.Étapes
. Téléchargez le fichier wfa_ocsetup.exe dans un répertoire du serveur DataFabric Manager 5.x à l'emplacement suivant : _https_://WFA_Server_IP/download/wfa_ocsetup.exe.
+
_WFA_Server_IP_ est l'adresse IP (adresse IPv4 ou IPv6) de votre serveur WFA.

+
Si vous avez spécifié un port non-par défaut pour WFA, vous devez inclure le numéro de port comme suit : _https_://wfa_Server_ip:port/download/wfa_ocsetup.exe.

+
_Port_ est le numéro de port TCP que vous avez utilisé pour le serveur WFA au cours de l'installation.

+
Si vous spécifiez une adresse IPv6, vous devez l'inclure entre crochets.

. Double-cliquez sur le fichier wfa_ocsetup.exe.
. Lisez les informations de l'assistant d'installation et cliquez sur *Suivant*.
. Parcourez ou tapez l'emplacement OpenJDK et cliquez sur *Suivant*.
. Saisissez un nom d'utilisateur et un mot de passe pour remplacer les informations d'identification par défaut.
+
Un nouveau compte utilisateur de base de données est créé avec accès à la base de données DataFabric Manager 5.x.

+

NOTE: Si vous ne créez pas de compte d'utilisateur, les informations d'identification par défaut sont utilisées. Vous devez créer un compte utilisateur pour des raisons de sécurité.

. Cliquez sur *Suivant* et examinez les résultats.
. Cliquez sur *Suivant*, puis sur *Terminer* pour terminer l'assistant.

