---
permalink: windows-install/task-reset-the-admin-password-created-during-installation.html 
sidebar: sidebar 
keywords: reset, admin password, created, installation 
summary: 'Si vous avez oublié le mot de passe de l"utilisateur admin que vous avez créé lors de l"installation du serveur OnCommand Workflow Automation (WFA), vous pouvez réinitialiser le mot de passe.' 
---
= Réinitialise le mot de passe d'administration créé lors de l'installation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez oublié le mot de passe de l'utilisateur admin que vous avez créé lors de l'installation du serveur OnCommand Workflow Automation (WFA), vous pouvez réinitialiser le mot de passe.

* Vous devez disposer de privilèges d'administrateur pour le système Windows sur lequel vous avez installé WFA.
* Les services WFA doivent être en cours d'exécution.
* Cette procédure réinitialise uniquement le mot de passe de l'utilisateur admin qui a été créé lors de l'installation de WFA.
+
Vous ne pouvez pas réinitialiser le mot de passe des autres utilisateurs admin de WFA que vous avez créés après l'installation de WFA.

* Cette procédure n'applique pas la stratégie de mot de passe que vous avez configurée.
+
Vous devez entrer un mot de passe conforme à la politique de mots de passe, ou modifier ce mot de passe depuis l'interface utilisateur WFA après avoir réinitialisé le mot de passe.



.Étapes
. Ouvrez une invite de commande et accédez au répertoire suivant : `WFA_install_location\WFA\bin\`
. Saisissez la commande suivante :
+
`wfa --admin-password [--password=PASS]`

+
Si vous ne fournissez pas de mot de passe dans la commande, vous devez entrer le mot de passe lorsque vous y êtes invité.

. À l'invite de commande, suivez les instructions à l'écran pour réinitialiser le mot de passe d'administration.

