---
permalink: windows-install/task-modify-the-default-password-policy-windows.html 
sidebar: sidebar 
keywords: modify, default, password policy, windows 
summary: 'OnCommand Workflow Automation (WFA) applique une politique de mots de passe aux utilisateurs locaux. Vous pouvez modifier la stratégie de mot de passe par défaut pour définir un mot de passe selon vos besoins.' 
---
= Modifier la stratégie de mot de passe par défaut pour Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) applique une politique de mots de passe aux utilisateurs locaux. Vous pouvez modifier la stratégie de mot de passe par défaut pour définir un mot de passe selon vos besoins.

Vous devez être connecté au système hôte WFA en tant qu'utilisateur root.

* Le chemin d'installation par défaut de WFA est utilisé dans cette procédure.
+
Si vous avez modifié l'emplacement par défaut lors de l'installation, vous devez utiliser le chemin d'installation personnalisé de WFA.

* La commande permettant de modifier la stratégie de mots de passe par défaut est .\wfa --password-policy=default.
+
Le paramètre par défaut est "minLength=true,8;specialChar=true,1;digitalChar=true,1;lowercasChar=true,1;uppercaseChar=true,1;blanceChar=false`. Conformément à ce paramètre pour la stratégie de mot de passe par défaut, le mot de passe doit comporter au moins huit caractères, au moins un caractère spécial, un chiffre, un caractère minuscule et un caractère majuscule et ne doit pas contenir d'espace.



.Étapes
. À l'invite de commande, accédez au répertoire suivant sur le serveur WFA:
+
`WFA_install_location/wfa/bin/`

. Modifier la stratégie de mots de passe par défaut :
+
`.\wfa --password-policy=PasswordPolicyString --restart=WFA`


