---
permalink: windows-install/task-add-active-directory-group-names.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, add, active directory groups 
summary: 'Vous pouvez ajouter des groupes Active Directory dans OnCommand Workflow Automation (WFA).' 
---
= Ajouter des groupes Active Directory
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter des groupes Active Directory dans OnCommand Workflow Automation (WFA).

.Étapes
. Connectez-vous à WFA via un navigateur Web en tant qu'administrateur.
. Cliquez sur *Paramètres* et sous *gestion*, cliquez sur *groupes Active Directory*.
. Dans la fenêtre groupes Active Directory, cliquez sur l'icône *Nouveau*.
. Dans la boîte de dialogue Nouveau groupe Active Directory, entrez les informations requises.
+
Si vous sélectionnez *approbateur* dans la liste déroulante *rôle*, il est recommandé de fournir l'ID e-mail de l'approbateur. S'il existe plusieurs approbateurs, vous pouvez fournir un ID d'e-mail de groupe dans le champ *E-mail*. Sélectionnez les différents événements du flux de travail pour lesquels la notification doit être envoyée au groupe Active Directory en particulier.

. Cliquez sur *Enregistrer*.

