---
permalink: windows-install/task-restore-full-the-oncommand-workflow-automation-database-using-rest-apis.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, restore, wfa, database, rest, apis 
summary: 'Vous pouvez effectuer une restauration complète de la base de données OnCommand Workflow Automation (WFA) à l"aide d"API REST. Dans un cadre de restauration complète, vous pouvez restaurer la base de données WFA, la configuration WFA et la clé.' 
---
= Restaurez (complète) la base de données WFA à l'aide d'API REST
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer une restauration complète de la base de données OnCommand Workflow Automation (WFA) à l'aide d'API REST. Dans un cadre de restauration complète, vous pouvez restaurer la base de données WFA, la configuration WFA et la clé.

* Vous devez avoir créé une sauvegarde .zip de la base de données WFA.
* Vous devez disposer d'informations d'identification admin ou Architect.
* Si vous restaurez la base de données dans le cadre de la procédure de migration, vous devez effectuer une restauration complète.


.Étapes
. Entrez l'URL suivante dans le navigateur du client REST : `+https://IP address of WFA server/rest/backups?full=true+`
. Dans la fenêtre sauvegarde, sélectionnez la méthode *POST*.
. Dans la liste déroulante *part*, sélectionnez *corps multipièce*.
. Dans le champ *fichier*, saisissez les informations suivantes :
+
.. Dans la liste déroulante *Type de contenu*, sélectionnez *multipièce/données-formulaire*.
.. Dans la liste déroulante *Charset*, sélectionnez *ISO-8859-1*.
.. Dans le champ *Nom de fichier*, entrez le nom du fichier de sauvegarde que vous avez créé et que vous souhaitez restaurer.
.. Cliquez sur *Parcourir*.
.. Sélectionnez l'emplacement du fichier de sauvegarde .zip.


. Accédez au répertoire WFA_install_location\wfa\bin, puis redémarrez les services WFA :
. Redémarrez les services *NetApp WFA Database* et *NetApp WFA Server* :
+
`wfa --restart`

. Vérifiez que l'opération de restauration est réussie et que WFA est accessible.

