---
permalink: windows-install/task-disable-the-default-password-policy.html 
sidebar: sidebar 
keywords: disable, default, password policy 
summary: 'OnCommand Workflow Automation (WFA) est configuré pour appliquer une politique de mots de passe aux utilisateurs locaux. Si vous ne souhaitez pas utiliser la stratégie de mot de passe, vous pouvez la désactiver.' 
---
= Désactivez la stratégie de mot de passe par défaut
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) est configuré pour appliquer une politique de mots de passe aux utilisateurs locaux. Si vous ne souhaitez pas utiliser la stratégie de mot de passe, vous pouvez la désactiver.

Vous devez avoir ouvert une session sur le système hôte WFA en tant qu'administrateur.

Le chemin d'installation par défaut de WFA est utilisé dans cette procédure. Si vous avez modifié l'emplacement par défaut lors de l'installation, vous devez utiliser le chemin d'installation WFA modifié.

.Étapes
. Ouvrez l'Explorateur Windows et accédez au répertoire suivant : `WFA_install_location\WFA\bin\.`
. Double-cliquez sur le fichier ps.cmd.
+
Une invite d'interface de ligne de commande PowerShell s'ouvre avec les modules ONTAP et WFA chargés.

. À l'invite, saisissez les informations suivantes :
+
`Set-WfaConfig -Name PasswordPolicy -Enable $false`

. Lorsque vous y êtes invité, redémarrez les services WFA.

