---
permalink: help/reference-new-command-definition-dialog-box.html 
sidebar: sidebar 
keywords: new, command, definition, dialog box, enable, define, create, workflow, predefined, meet, requirements 
summary: La boîte de dialogue Nouvelle définition de commande vous permet de définir une nouvelle commande. Vous pouvez créer de nouvelles commandes pour vos flux de travail si les commandes prédéfinies ne répondent pas à vos exigences. 
---
= Nouvelle boîte de dialogue Définition de commande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La boîte de dialogue Nouvelle définition de commande vous permet de définir une nouvelle commande. Vous pouvez créer de nouvelles commandes pour vos flux de travail si les commandes prédéfinies ne répondent pas à vos exigences.

* Onglet Propriétés
* Onglet Code
* Onglet Définition des paramètres
* Mappage des paramètres
* Onglet réservation
* Onglet Vérification




== Onglet Propriétés

Vous permet de spécifier les propriétés de la commande, telles que le nom, la description et la version d'entité.

* *Nom*
+
Vous permet de spécifier un nom pour la commande. Vous devez spécifier un nom pour enregistrer la commande.

* *Version entité*
+
Vous permet de spécifier le numéro de version de la commande dans `major.minor.revision` format--par exemple, 1.0.0.

* *Description*
+
Permet de saisir une description pour la commande.

* *Représentation de chaîne*
+
Permet de spécifier une représentation de chaîne pour la commande à l'aide de la syntaxe MVFLEX expression Language (MVEL).

+
Vous devez spécifier la représentation de chaîne pour enregistrer la commande. La représentation de chaîne est utilisée pour afficher les détails de la commande dans la conception du workflow lors de la planification et de l'exécution. Vous devez utiliser uniquement les paramètres d'une commande dans la représentation de chaîne pour cette commande.

* *Délai (s)*
+
Vous permet de spécifier la valeur de temporisation (en secondes) pour la commande. La valeur par défaut est 600 secondes.

* *Type de commande*
+
Vous permet de spécifier le type d'exécution de la commande.

+
** *Exécution standard*
+
Permet d'exécuter la commande sans délai d'attente. L'exécution standard est sélectionnée par défaut.

** *Attendre la condition*
+
Vous permet de spécifier le temps (en secondes) pendant lequel la commande doit attendre avant l'exécution. La valeur par défaut est 60 secondes.



* *Versions logicielles minimales*
+
Spécifie les versions minimales du logiciel requises pour le fonctionnement de la commande. À titre d'exemple, le logiciel peut être Clustered Data ONTAP 8.2.0 et vCenter 6.0. Les versions s'affichent sous forme de valeurs séparées par des virgules.





== Onglet Code

Permet de saisir le code de la commande dans le langage de script sélectionné. Vous pouvez ajouter un nouveau langage de script en sélectionnant la langue requise dans la liste déroulante langage de script.

* *Paramètres de découverte*
+
Copie les paramètres définis dans le code PowerShell dans la table Définition des paramètres et dans la table mappage des paramètres.





== Onglet Définition des paramètres

Affiche les paramètres définis dans le code que vous avez saisi dans l'onglet Code.

* *Nom*
+
Affiche le nom du paramètre.

* *Description*
+
Affiche la description du paramètre.

* *Obligatoire*
+
Affiche une case à cocher sélectionnée pour les paramètres obligatoires.

* *Type*
+
Affiche le type du paramètre, tel que chaîne, enum, matrice ou mot de passe.

* *Valeurs*
+
Affiche la valeur définie pour le paramètre.

* *Ajouter un paramètre*
+
Permet d'ajouter un paramètre à la commande si le langage de script sélectionné est Perl.

* *Supprimer le paramètre*
+
Permet de supprimer un paramètre de la commande si le langage de script sélectionné est Perl.





== Mappage des paramètres

Vous permet de mapper les paramètres aux objets de dictionnaire et de spécifier l'attribut et le nom de l'objet.

* *Nom*
+
Affiche le nom du paramètre.

* *Type*
+
Permet de sélectionner un objet de dictionnaire pour le paramètre.

* *Attribut*
+
Vous permet de spécifier l'attribut requis. Vous pouvez sélectionner l'attribut (si disponible) ou entrer l'attribut.

* *Nom de l'objet*
+
Vous permet de spécifier un nom pour l'objet dictionnaire.





== Onglet réservation

Vous permet de réserver les ressources nécessaires à la commande.

* *Script de réservation*
+
Vous permet de saisir une requête SQL pour réserver les ressources requises par la commande. Cela permet de s'assurer que les ressources sont disponibles lors de l'exécution d'un flux de travail planifié.

* * Représentation de réservation*
+
Permet de spécifier une représentation de chaîne pour la réservation à l'aide de la syntaxe MVEL. La représentation de chaîne est utilisée pour afficher les détails de la réservation dans la fenêtre Réservations.





== Onglet Vérification

Permet de vérifier une réservation et de la supprimer une fois la commande exécutée.

* *Script de vérification*
+
Vous permet d'entrer une requête SQL pour vérifier l'utilisation des ressources réservées par le script de réservation. Le script de vérification vérifie également si le cache WFA est mis à jour et supprime la réservation après l'acquisition d'un cache.

* *Vérification test*
+
Ouvre la boîte de dialogue Vérification, qui permet de tester les paramètres du script de vérification.





== Boutons de commande

* *Test*
+
Ouvre la commande Test <CommandName> dans la boîte de dialogue <ScriptLanguage>, qui vous permet de tester la commande.

* *Enregistrer*
+
Enregistre la commande et ferme la boîte de dialogue.

* *Annuler*
+
Annule les modifications, le cas échéant, et ferme la boîte de dialogue.


