---
permalink: help/reference-clone-template-dialog-box.html 
sidebar: sidebar 
keywords: clone, template, dialog box, enable, create, copy, template, edit 
summary: La boîte de dialogue Cloner le modèle vous permet de créer une copie du modèle et de le modifier. 
---
= Boîte de dialogue Cloner le modèle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La boîte de dialogue Cloner le modèle vous permet de créer une copie du modèle et de le modifier.

* *Nom*
+
Permet de modifier le nom du modèle.

* *Type*
+
Permet de sélectionner un objet de dictionnaire dans la liste. Le nom du modèle que vous avez sélectionné pour le clone est utilisé comme nom du clone, puis ajouté - copie par défaut.

* *Version entité*
+
Vous permet de saisir le numéro de version du modèle dans `major.minor.revision` format--par exemple, 1.0.0.

* *Description*
+
Permet de modifier la description du modèle.

* *Attributs*
+
Affiche les attributs de l'objet dictionnaire sélectionné et vous permet de saisir une valeur pour chaque attribut, tel que l'énumération et la fonction.





== Boutons de commande

* *Enregistrer*
+
Enregistre le modèle et ferme la boîte de dialogue.

* *Annuler*
+
N'enregistre pas le modèle et ferme la boîte de dialogue.


