---
permalink: help/reference-clone-finder-dialog-box.html 
sidebar: sidebar 
keywords: clone, finder, dialog box, enable, create, copy, finder, edit 
summary: La boîte de dialogue Cloner le Finder vous permet de créer une copie du Finder et de modifier le Finder cloné. 
---
= Boîte de dialogue du moteur de recherche de clones
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La boîte de dialogue Cloner le Finder vous permet de créer une copie du Finder et de modifier le Finder cloné.

* Onglet Propriétés
* Filtres
* Onglet attributs retournés




== Onglet Propriétés

L'onglet Propriétés vous permet de modifier le nom du Finder, le type d'objet et la description du Finder. L'onglet affiche également les paramètres d'entrée du filtre utilisé dans le Finder.

* *Nom*
+
Permet de modifier le nom du Finder. Le nom du Finder que vous avez sélectionné pour le clone est utilisé en tant que nom du clone, puis ajouté à celui-ci `- copy` par défaut.

* *Type*
+
Permet de sélectionner le type d'objet dans la liste. Les filtres de l'objet sélectionné s'affichent dans l'onglet filtres.

* *Version entité*
+
Permet de saisir le numéro de version du Finder dans `major.minor.revision` format--par exemple, 1.0.0.

* *Description*
+
Permet de modifier la description du Finder.

* *Tableau des paramètres d'entrée*
+
Affiche les paramètres d'entrée des filtres sélectionnés.





== L'onglet filtres

Vous permet de sélectionner les filtres requis dans la liste des filtres disponibles.

* *Filtres disponibles*
+
Affiche la liste des filtres disponibles pour l'objet sélectionné dans l'onglet Propriétés.

* *Filtres sélectionnés*
+
Affiche la liste des filtres sélectionnés dans les filtres disponibles.

* *Boutons de sélection*
+
Vous permet de déplacer l'entrée sélectionnée d'une boîte à l'autre.





== Onglet attributs retournés

Vous permet de voir les détails des filtres disponibles, de sélectionner les attributs requis des filtres disponibles et de spécifier l'ordre de tri des attributs.

* *Disponible*
+
Affiche les filtres disponibles et les attributs des filtres.

* *Sélectionné*
+
Affiche les filtres sélectionnés et les attributs, les alias et l'ordre de tri des filtres sélectionnés.

* *Boutons de commande*
+
** *Haut*
+
Déplace l'entrée sélectionnée d'une ligne vers le haut dans le tableau sélectionné.

** *Bas*
+
Déplace l'entrée sélectionnée d'une ligne vers le bas dans le tableau sélectionné.

** *Boutons de sélection*
+
Déplace l'entrée sélectionnée d'une table vers une autre.







== Boutons de commande

* *Test*
+
Permet de tester le viseur que vous avez sélectionné pour le cloner.

* *Enregistrer*
+
Enregistre le Finder et ferme la boîte de dialogue.

* *Annuler*
+
Annule les modifications, le cas échéant, et ferme la boîte de dialogue.


