---
permalink: help/reference-clone-command-definition-dialog-box.html 
sidebar: sidebar 
keywords: clone, command, definition, dialog box, enable, copy, edit 
summary: La boîte de dialogue Cloner la définition des commandes vous permet de copier une commande et de modifier la commande clonée. 
---
= Cloner la boîte de dialogue Définition de la commande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La boîte de dialogue Cloner la définition des commandes vous permet de copier une commande et de modifier la commande clonée.

* Onglet Propriétés
* Onglet Code
* Onglet Définition des paramètres
* Mappage des paramètres
* Onglet réservation
* Onglet Vérification




== Onglet Propriétés

Permet de modifier les propriétés de la commande clonée, comme le nom, la description et la version de l'entité.

* *Nom*
+
Permet de modifier le nom de la commande clonée. Par défaut, le nom de la commande que vous avez sélectionnée pour cloner est utilisé comme nom pour le clone, ajouté à «»- copy`.

* *Version entité*
+
Permet de modifier le numéro de version de la commande dans `major.minor.revision` format--par exemple, 1.0.0.

* *Description*
+
Permet de modifier la description de la commande.

* *Représentation de chaîne*
+
Permet de spécifier une représentation de chaîne pour la commande à l'aide de la syntaxe MVFLEX expression Language (MVEL). Vous devez spécifier la représentation de chaîne pour enregistrer la commande.

* *Délai (s)*
+
Vous permet de spécifier la valeur de temporisation (en secondes) pour la commande. La valeur par défaut est 600 secondes.

* *Type de commande*
+
Vous permet de spécifier le type d'exécution de la commande.

+
** *Exécution standard*
+
Permet d'exécuter la commande sans délai d'attente. L'exécution standard est sélectionnée par défaut.

** *Attendre la condition*
+
Vous permet de spécifier le temps (en secondes) pendant lequel la commande doit attendre avant l'exécution. La valeur par défaut est 60 secondes.



* *Versions logicielles minimales*
+
Spécifie les versions minimales du logiciel requises pour le fonctionnement de la commande. À titre d'exemple, le logiciel peut être Clustered Data ONTAP 8.2.0 et vCenter 6.0. Les versions s'affichent sous forme de valeurs séparées par des virgules.

* *Conserver les scripts de réservation et de vérification à partir de la commande d'origine*
+
Permet de conserver les scripts de réservation et de vérification qui ont été spécifiés à l'origine pour la commande que vous souhaitez cloner.





== Onglet Code

Permet de modifier le code de la commande.

* *Paramètres de découverte*
+
Copie les paramètres définis dans le code PowerShell dans la table Définition des paramètres et dans la table mappage des paramètres.





== Onglet Définition des paramètres

Affiche les paramètres définis dans le code que vous avez saisi dans l'onglet Code.

* *Nom*
+
Affiche le nom du paramètre.

* *Description*
+
Affiche la description du paramètre.

* *Obligatoire*
+
Affiche une case à cocher sélectionnée pour les paramètres obligatoires.

* *Type*
+
Affiche le type du paramètre, tel que chaîne ou enum.

* *Valeurs*
+
Affiche les valeurs définies pour le paramètre.

* *Ajouter un paramètre*
+
Permet d'ajouter un paramètre à la commande si le langage de script sélectionné est Perl.

* *Supprimer le paramètre*
+
Permet de supprimer un paramètre de la commande si le langage de script sélectionné est Perl.





== Mappage des paramètres

Vous permet de mapper les paramètres aux objets de dictionnaire et de spécifier l'attribut et le nom de l'objet.

* *Nom*
+
Affiche le nom du paramètre.

* *Type*
+
Permet de sélectionner un objet de dictionnaire pour le paramètre.

* *Attribut*
+
Vous permet de spécifier l'attribut requis. Vous pouvez sélectionner l'attribut (si disponible) ou saisir le nom de l'attribut.

* *Nom de l'objet*
+
Vous permet de spécifier un nom pour l'objet dictionnaire.





== Onglet réservation

Vous permet de réserver les ressources nécessaires à la commande.

* *Script de réservation*
+
Vous permet de saisir une requête SQL pour réserver les ressources requises par la commande. Cela permet de s'assurer que les ressources requises sont disponibles lors de l'exécution d'un flux de travail planifié.

* * Représentation de réservation*
+
Permet de spécifier une représentation de chaîne pour la réservation à l'aide de la syntaxe MVEL. La représentation de chaîne est utilisée pour afficher les détails de la réservation dans la fenêtre Réservations.





== Onglet Vérification

Permet de vérifier une réservation et de la supprimer une fois la commande exécutée.

* *Script de vérification*
+
Vous permet d'entrer une requête SQL pour vérifier l'utilisation des ressources réservées par le script de réservation. Le script de vérification vérifie également si le cache WFA est mis à jour et supprime la réservation après l'acquisition d'un cache.

* *Vérification test*
+
Ouvre la boîte de dialogue Vérification, qui permet de tester les paramètres du script de vérification.





== Boutons de commande

* *Test*
+
Ouvre la commande Test <CommandName> dans la boîte de dialogue <ScriptLanguage>, qui vous permet de tester la commande.

* *Enregistrer*
+
Enregistre la commande et ferme la boîte de dialogue.

* *Annuler*
+
Annule les modifications, le cas échéant, et ferme la boîte de dialogue.


