---
permalink: help/reference-edit-template-dialog-box.html 
sidebar: sidebar 
keywords: edit, template, dialog box, enable 
summary: La boîte de dialogue Modifier le modèle vous permet de modifier un modèle. 
---
= Boîte de dialogue Modifier le modèle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La boîte de dialogue Modifier le modèle vous permet de modifier un modèle.

* *Nom*
+
Permet de modifier le nom du modèle.

* *Type*
+
Permet de sélectionner un objet de dictionnaire dans la liste.

* *Version entité*
+
Vous permet de saisir le numéro de version du modèle dans `major.minor.revision` format--par exemple, 1.0.0.

* *Description*
+
Permet de modifier la description du modèle.

* *Attributs*
+
Affiche les attributs de l'objet dictionnaire sélectionné et vous permet de saisir une valeur pour chaque attribut, tel que l'énumération et la fonction.





== Boutons de commande

* *Enregistrer*
+
Enregistre les modifications et ferme la boîte de dialogue.

* *Annuler*
+
N'enregistre pas les modifications, le cas échéant, et ferme la boîte de dialogue.


