---
permalink: help/reference-new-finder-dialog-box.html 
sidebar: sidebar 
keywords: new, finder, dialog box, enable, create 
summary: La boîte de dialogue Nouveau Finder vous permet de créer de nouveaux finders. 
---
= Boîte de dialogue Nouveau Finder
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La boîte de dialogue Nouveau Finder vous permet de créer de nouveaux finders.

* Onglet Propriétés
* Filtres
* Onglet attributs retournés




== Onglet Propriétés

L'onglet *Propriétés* vous permet de spécifier un nom pour le Finder, de sélectionner le type d'objet dictionnaire WFA et de saisir une description pour le Finder. L'onglet affiche également les paramètres d'entrée après qu'un filtre a été sélectionné dans l'onglet *filtres*.

* *Nom*
+
Permet d'entrer un nom pour le Finder.

* *Type*
+
Vous permet de sélectionner le type d'objet dans la liste tels que l'agrégat, le groupe initiateur et le cluster. Les filtres de l'objet sélectionné sont affichés dans l'onglet *filtres*.

* *Version entité*
+
Permet de saisir le numéro de version du Finder dans `major.minor.revision` format--par exemple, 1.0.0.

* *Description*
+
Permet de saisir une description pour le Finder.

* *Tableau des paramètres d'entrée*
+
Affiche les paramètres d'entrée des filtres sélectionnés.





== L'onglet filtres

Vous permet de sélectionner les filtres requis dans la liste des filtres disponibles.

* *Filtres disponibles*
+
Affiche la liste des filtres disponibles pour l'objet sélectionné dans l'onglet *Propriétés*.

* *Filtres sélectionnés*
+
Affiche la liste des filtres sélectionnés dans les filtres disponibles.

* *Boutons de sélection*
+
Déplace l'entrée sélectionnée d'une case à l'autre.





== Onglet attributs retournés

Vous permet d'afficher des détails sur les filtres disponibles, de sélectionner les attributs requis des filtres disponibles et de spécifier l'ordre de tri des attributs.

* *Disponible*
+
Affiche les filtres disponibles et les attributs des filtres.

* *Sélectionné*
+
Affiche les filtres sélectionnés et les attributs, les alias et l'ordre de tri des filtres sélectionnés.

* *Boutons de commande*
+
** *Haut*
+
Déplace l'entrée sélectionnée d'une ligne vers le haut dans le tableau sélectionné.

** *Bas*
+
Déplace l'entrée sélectionnée d'une ligne vers le bas dans le tableau sélectionné.

** *Boutons de sélection*
+
Déplace l'entrée sélectionnée d'une table vers une autre.







== Boutons de commande

* *Test*
+
Vous permet de tester le viseur que vous avez défini.

* *Enregistrer*
+
Enregistre le Finder et ferme la boîte de dialogue.

* *Annuler*
+
N'enregistre pas le Finder et ferme la boîte de dialogue.


