---
permalink: help/reference-edit-credentials-dialog-box.html 
sidebar: sidebar 
keywords: edit, credential, dialog box, enable, modify, exist 
summary: 'La boîte de dialogue Modifier les informations d"identification permet de modifier une information d"identification existante.' 
---
= Boîte de dialogue Modifier les informations d'identification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La boîte de dialogue Modifier les informations d'identification permet de modifier une information d'identification existante.



== Paramètres d'informations d'identification

* * Correspondance*
+
Vous permet de sélectionner le type de correspondance des informations d'identification, qui définit les informations d'identification pour une adresse IP ou un nom d'hôte spécifique, ou pour un sous-réseau ou une plage IP entière. Les options disponibles sont les suivantes :

+
** Exact : définit une adresse IP ou un nom d'hôte spécifique
** Modèle : définit une plage de sous-réseaux ou d'adresses IP entière


* *Type*
+
Vous permet de sélectionner le type d'informations d'identification dans la liste déroulante.

+
VMware vCenter n'est pas pris en charge pour Linux.

* *Nom/IP*
+
Vous permet de spécifier le nom d'hôte ou l'adresse IP pour les informations d'identification.

* *Nom d'utilisateur*
+
Vous permet de spécifier le nom d'utilisateur pour les informations d'identification.

* *Mot de passe*
+
Vous permet de spécifier le mot de passe du nom d'utilisateur.

* *Écraser les valeurs par défaut*
+
Vous permet de remplacer les valeurs par défaut du protocole, du port et du délai d'attente associés au type de système distant sélectionné pour les informations d'identification.

+
Par défaut, cette case n'est pas cochée. Vous devez cocher la case pour remplacer les valeurs par défaut.





== Tableau des protocoles

La table des protocoles affiche les numéros de port et les limites de délai (en secondes) pour les protocoles associés au système distant sélectionné pour les informations d'identification.



== Boutons de commande

* *Test*
+
Vous permet de tester la connexion au nom d'hôte ou à l'adresse IP en vous connectant à l'aide des informations d'identification requises.

* *Enregistrer*
+
Enregistre les paramètres de configuration et ferme la boîte de dialogue.

* *Annuler*
+
Annule les modifications, le cas échéant, et ferme la boîte de dialogue.


