---
permalink: help/reference-new-credentials-dialog-box.html 
sidebar: sidebar 
keywords: new, credential, dialog box, enable, create 
summary: 'La boîte de dialogue nouvelles informations d"identification vous permet de créer une nouvelle information d"identification.' 
---
= Nouvelle boîte de dialogue informations d'identification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La boîte de dialogue nouvelles informations d'identification vous permet de créer une nouvelle information d'identification.



== Paramètres d'informations d'identification

Vous pouvez définir les paramètres suivants pour les informations d'identification nouvellement créées :

* * Correspondance*
+
Vous permet de sélectionner le type de correspondance des informations d'identification, qui définit les informations d'identification pour une adresse IP ou un nom d'hôte spécifique, ou pour un sous-réseau ou une plage IP entière. Vous pouvez sélectionner l'une des options suivantes :

+
** Exact : définit les informations d'identification d'une adresse IP ou d'un nom d'hôte spécifique
** Modèle : définit les informations d'identification de la plage de noms d'hôte ou de l'ensemble du sous-réseau ou de la plage IP
+
La répétition est une expression régulière utilisée pour la correspondance d'une chaîne. Par exemple : `10.10.10.` Correspond à n'importe quel IP compris entre 10.10.10.0 et 10.10.10.255, et `host` correspond à tous les noms d'hôte commençant par `host`.



* *Type*
+
Permet de sélectionner le type d'hôte dans la liste déroulante.

+

NOTE: VMware vCenter n'est pas pris en charge pour Linux.

* *Nom/IP*
+
Vous permet de spécifier le nom d'hôte ou l'adresse IP pour les informations d'identification.

* *Nom d'utilisateur*
+
Vous permet de spécifier un nom d'utilisateur pour les informations d'identification.

* *Mot de passe*
+
Vous permet de spécifier un mot de passe pour le nom d'utilisateur que vous avez créé pour les informations d'identification.

* *Écraser les valeurs par défaut*
+
Vous permet de remplacer les valeurs par défaut du protocole, du port et du délai d'attente associés au type de système distant sélectionné pour les informations d'identification.

+
Par défaut, cette case n'est pas cochée. Vous devez cocher la case pour remplacer les valeurs par défaut.





== Boutons de commande

* *Test*
+
Vous permet de tester la connexion à l'hôte ou à l'adresse IP en vous connectant à l'aide des informations d'identification requises.

* *Enregistrer*
+
Enregistre les paramètres de configuration et ferme la boîte de dialogue.

* *Annuler*
+
Annule les modifications, le cas échéant, et ferme la boîte de dialogue.


