---
permalink: help/task-configure-a-database-user-by-running-ocsetup-on-linux.html 
sidebar: sidebar 
keywords: run, ocstep, datafabric, manager, server, configure, read-only, access, oncommand, workflow, automation 
summary: 'Vous pouvez exécuter le fichier ocsetup sur le serveur DataFabric Manager 5.x pour configurer l"accès en lecture seule de la base de données DataFabric Manager 5.x à OnCommand Workflow Automation.' 
---
= Configurez un utilisateur de base de données en exécutant ocsetup sous Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter le `ocsetup` Sur le serveur DataFabric Manager 5.x, configurez l'accès en lecture seule de la base de données DataFabric Manager 5.x à OnCommand Workflow Automation.

.Étapes
. Téléchargez le `wfa_ocsetup.sh` File dans votre répertoire personnel sur le serveur DataFabric Manager 5.x à l'aide de la commande suivante dans le terminal :
+
`+wget https://WFA_Server_IP/download/wfa_ocsetup.sh+`

+
_WFA_Server_IP_ est l'adresse IP (adresse IPv4 ou IPv6) de votre serveur WFA.

+
Si vous avez spécifié un port non par défaut pour WFA, vous devez inclure le numéro de port comme suit :

+
`+wget https://wfa_server_ip:port/download/wfa_ocsetup.sh+`

+
_Port_ est le numéro de port TCP que vous avez utilisé pour le serveur WFA au cours de l'installation.

+
Si vous spécifiez une adresse IPv6, vous devez l'inclure entre crochets.

. Utiliser la commande suivante dans le terminal pour modifier le `wfa_ocsetup.sh` fichier vers un exécutable :
+
 `chmod +x wfa_ocsetup.sh`
. Exécutez le script en saisissant les éléments suivants dans le terminal :
+
`./wfa_ocsetup.sh OpenJDK_path`

+
_OpenJDK_PATH_ est le chemin d'accès à OpenJDK.

+
Exemple

+
`/opt/NTAPdfm/java`

+
La sortie suivante s'affiche sur le terminal, indiquant que la configuration a réussi :

+
[listing]
----
Verifying archive integrity... All good.
Uncompressing WFA OnCommand Setup.....
*** Welcome to OnCommand Setup Utility for Linux ***
    <Help information>
*** Please override the default credentials below ***
Override DB Username [wfa] :
----
. Saisissez un nom d'utilisateur et un mot de passe pour remplacer les informations d'identification par défaut.
+
Un nouveau compte utilisateur de base de données est créé avec accès à la base de données DataFabric Manager 5.x.

+

NOTE: Si vous ne créez pas de compte d'utilisateur, les informations d'identification par défaut sont utilisées. Vous devez créer un compte utilisateur pour des raisons de sécurité.

+
La sortie suivante s'affiche sur le terminal, indiquant que la configuration a réussi :

+
[listing]
----
***** Start of response from the database *****
>>> Connecting to database
<<< Connected
*** Dropped existing 'wfa' user
=== Created user 'username'
>>> Granting access
<<< Granted access
***** End of response from the database *****
***** End of Setup *****
----

